name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

    # client
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (client)
        run: |
          cd client
          npm install
      - name: Build client
        run: |
          cd client
          npm run build

    # server
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies (server)
        run: |
          cd server
          
          poetry install          
      - name: Run server tests
        run: |
          cd server
          pytest || true

    # deploy client
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./client/dist
            publish_branch: gh-pages
            cname: thefayettevillains.com
